// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package dataloader

import (
	"sync"
	"time"

	"github.com/ryutah/go-graphql-photo-share-api/domain/model"
)

// PostedPhotoLoaderConfig captures the config to create a new PostedPhotoLoader
type PostedPhotoLoaderConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []model.UserID) ([][]*model.Photo, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewPostedPhotoLoader creates a new PostedPhotoLoader given a fetch, wait, and maxBatch
func NewPostedPhotoLoader(config PostedPhotoLoaderConfig) *PostedPhotoLoader {
	return &PostedPhotoLoader{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// PostedPhotoLoader batches and caches requests
type PostedPhotoLoader struct {
	// this method provides the data for the loader
	fetch func(keys []model.UserID) ([][]*model.Photo, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[model.UserID][]*model.Photo

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *postedPhotoLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type postedPhotoLoaderBatch struct {
	keys    []model.UserID
	data    [][]*model.Photo
	error   []error
	closing bool
	done    chan struct{}
}

// Load a Photo by key, batching and caching will be applied automatically
func (l *PostedPhotoLoader) Load(key model.UserID) ([]*model.Photo, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a Photo.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *PostedPhotoLoader) LoadThunk(key model.UserID) func() ([]*model.Photo, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() ([]*model.Photo, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &postedPhotoLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() ([]*model.Photo, error) {
		<-batch.done

		var data []*model.Photo
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *PostedPhotoLoader) LoadAll(keys []model.UserID) ([][]*model.Photo, []error) {
	results := make([]func() ([]*model.Photo, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	photos := make([][]*model.Photo, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		photos[i], errors[i] = thunk()
	}
	return photos, errors
}

// LoadAllThunk returns a function that when called will block waiting for a Photos.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *PostedPhotoLoader) LoadAllThunk(keys []model.UserID) func() ([][]*model.Photo, []error) {
	results := make([]func() ([]*model.Photo, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([][]*model.Photo, []error) {
		photos := make([][]*model.Photo, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			photos[i], errors[i] = thunk()
		}
		return photos, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *PostedPhotoLoader) Prime(key model.UserID, value []*model.Photo) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
		// and end up with the whole cache pointing to the same value.
		cpy := make([]*model.Photo, len(value))
		copy(cpy, value)
		l.unsafeSet(key, cpy)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *PostedPhotoLoader) Clear(key model.UserID) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *PostedPhotoLoader) unsafeSet(key model.UserID, value []*model.Photo) {
	if l.cache == nil {
		l.cache = map[model.UserID][]*model.Photo{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *postedPhotoLoaderBatch) keyIndex(l *PostedPhotoLoader, key model.UserID) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *postedPhotoLoaderBatch) startTimer(l *PostedPhotoLoader) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *postedPhotoLoaderBatch) end(l *PostedPhotoLoader) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
